name: Shuojiang Liu
avatar: images/profile.jpg # Avatar image. Default to "images/profile.webp".
bio: 'MS Student at Gerogia Tech'
# company: Company # HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
location: United States # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
# about: https://razonyang.com # The external about page. The internal about page will be used if not set.
params: {
  # layout: compact
}
# See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
social:
  email: shuojiang@gatech.edu
  github: LiuShuoJiang/blogs
  # twitter: razonyang
  # patreon: razonyang
  # paypal: razonyang
  rss: "" # Remove RSS
